version: "3.7"

services:
  web-server:
    env_file:
      - test.env
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: starter-nodejs-ava
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"